const fs = require('fs');
let content = fs.readFileSync('C:/Users/sebas/Desktop/ClaudeProjets/kinebilan/index.html', 'utf8');

// Find start and end of the exportPDF function
const start = content.indexOf('// ============================================================\n// EXPORT PDF');
// Find the UTILS section which follows
const end = content.indexOf('// ============================================================\r\n// UTILS');

console.log('start:', start, 'end:', end);
if (start === -1 || end === -1) process.exit(1);

// Build the new function using an array to avoid backtick escaping issues
const lines = [
  '// ============================================================',
  '// EXPORT PDF',
  '// ============================================================',
  'function exportPDF() {',
  '  var p = getPatient();',
  '  if (!p) return;',
  '',
  '  function esc(str) { return (str||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }',
  '',
  '  function hrow(label, value) {',
  '    if (!value) return "";',
  '    return "<tr><td style=\'font-weight:700;padding:3px 14px 3px 0;color:#126477;white-space:nowrap;font-size:10pt\'>"',
  '      + esc(label) + "</td><td style=\'padding:3px 0;color:#222;font-size:10pt\'>" + esc(value) + "</td></tr>";',
  '  }',
  '',
  '  function section(num, title, body) {',
  '    return "<div style=\'margin-bottom:28px\'>"',
  '      + "<div style=\'display:flex;align-items:center;gap:10px;margin-bottom:6px\'>"',
  '      + "<span style=\'display:flex;align-items:center;justify-content:center;width:24px;height:24px;min-width:24px;background:#126477;color:white;font-weight:700;font-size:11pt;border-radius:50%;\'>" + num + "</span>"',
  '      + "<span style=\'font-size:12pt;font-weight:700;color:#126477;text-transform:uppercase;letter-spacing:0.3px\'>" + title + "</span>"',
  '      + "</div>"',
  '      + "<div style=\'height:2px;background:linear-gradient(to right,#126477,#e0eef1);margin-bottom:10px;border-radius:1px\'></div>"',
  '      + "<div style=\'font-size:10.5pt;line-height:1.65;color:#222\'>" + body + "</div>"',
  '      + "</div>";',
  '  }',
  '',
  '  var sectionNum = 0;',
  '  function nextSection(title, body) { sectionNum++; return section(sectionNum, title, body); }',
  '',
  '  var patientName = ((p.prenom||"") + " " + (p.nom||"")).trim();',
  '  var prescInfo = p.prescripteur ? (p.prescripteur + (p.datePrescription ? " \u2014 ordonnance du " + p.datePrescription : "")) : "";',
  '',
  '  var headerBlock = "<div style=\'border:1.5px solid #126477;border-radius:6px;padding:16px 20px 12px;margin-bottom:24px;background:#f7fcfd\'>"',
  '    + "<div style=\'font-size:12pt;font-weight:700;color:#126477;text-align:center;margin-bottom:14px;text-transform:uppercase;letter-spacing:0.3px\'>COMPTE RENDU DE BILAN KIN\u00c9SITH\u00c9RAPIQUE VESTIBULAIRE</div>"',
  '    + "<table style=\'border-collapse:collapse;width:100%\'>"',
  '    + hrow("Patient", patientName)',
  '    + hrow("\u00c2ge", p.age ? p.age + " ans" : "")',
  '    + hrow("Profession", p.profession)',
  '    + hrow("Loisirs", p.loisirs)',
  '    + hrow("Date d\'\u00e9valuation", p.dateEval)',
  '    + hrow("Prescripteur", prescInfo)',
  '    + hrow("M\u00e9decin traitant", p.mt)',
  '    + hrow("Motif", p.motif)',
  '    + "</table></div>";',
  '',
  '  var sectionsHtml = "";',
  '  if (p.b1CR) sectionsHtml += nextSection("BILAN CLINIQUE", p.b1CR);',
  '  if (p.b2CR) sectionsHtml += nextSection("EXAMEN VIA R\u00c9ALIT\u00c9 VIRTUELLE", p.b2CR);',
  '',
  '  var imagesHtml = "";',
  '  if (p.captureVVS) {',
  '    imagesHtml += "<div style=\'page-break-before:always;text-align:center;padding-top:10px\'>"',
  '      + "<div style=\'font-weight:700;font-size:11pt;color:#126477;margin-bottom:16px;text-transform:uppercase\'>Verticale Visuelle Subjective (VVS)</div>"',
  '      + "<img src=\'" + p.captureVVS + "\' style=\'max-width:100%;max-height:180mm;border:1px solid #cde4ea;border-radius:6px\'/>"',
  '      + "</div>";',
  '  }',
  '  if (p.captureHCTSIB) {',
  '    imagesHtml += "<div style=\'page-break-before:always;text-align:center;padding-top:10px\'>"',
  '      + "<div style=\'font-weight:700;font-size:11pt;color:#126477;margin-bottom:16px;text-transform:uppercase\'>HCTSIB / Posturographie</div>"',
  '      + "<img src=\'" + p.captureHCTSIB + "\' style=\'max-width:100%;max-height:180mm;border:1px solid #cde4ea;border-radius:6px\'/>"',
  '      + "</div>";',
  '  }',
  '  if (imagesHtml) sectionsHtml += nextSection("EXAMENS GRAPHIQUES", imagesHtml);',
  '',
  '  var footer = "<div style=\'position:fixed;bottom:0;left:0;right:0;border-top:1.5px solid #126477;padding:6px 18mm 6px;text-align:center;background:white;font-family:Arial,sans-serif\'>"',
  '    + "<div style=\'font-weight:700;font-size:9.5pt;color:#126477\'>MACKAY S\u00e9bastien</div>"',
  '    + "<div style=\'font-size:8.5pt;color:#5a7a82\'>Masseur Kin\u00e9sith\u00e9rapeute D.E. &nbsp;|&nbsp; Cabinet de r\u00e9\u00e9ducation vestibulaire &nbsp;|&nbsp; DIU vertiges et r\u00e9\u00e9ducation vestibulaire PARIS VI<br>"',
  '    + "P\u00f4le Sant\u00e9 Argouges \u2014 42 rue de Beauvais, 14400 BAYEUX &nbsp;|&nbsp; 06.11.77.70.76 &nbsp;|&nbsp; sp.mck.kine@gmail.com</div>"',
  '    + "</div>";',
  '',
  '  var css = "@page{size:A4;margin:18mm 18mm 28mm 18mm}"',
  '    + "*{box-sizing:border-box;margin:0;padding:0}"',
  '    + "body{font-family:Arial,sans-serif;font-size:10.5pt;color:#1a1a1a;line-height:1.55}"',
  '    + "h1,h2,h3{font-size:11pt;color:#126477;margin:12px 0 4px}"',
  '    + "ul,ol{padding-left:20px;margin:4px 0}"',
  '    + "p{margin-bottom:6px}"',
  '    + "strong{color:#126477}"',
  '    + "@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}";',
  '',
  '  var html = "<!DOCTYPE html><html lang=\'fr\'><head><meta charset=\'utf-8\'/>"',
  '    + "<title>CR_" + esc(p.nom) + "_" + esc(p.prenom) + "_" + esc(p.dateEval||"bilan") + "</title>"',
  '    + "<style>" + css + "</style>"',
  '    + "</head><body>"',
  '    + headerBlock',
  '    + sectionsHtml',
  '    + footer',
  '    + "</body></html>";',
  '',
  '  var win = window.open("", "_blank");',
  '  win.document.write(html);',
  '  win.document.close();',
  '  win.onload = function() { win.focus(); win.print(); };',
  '',
  '  p.statut = "exporte";',
  '  p.lastMod = new Date().toLocaleString("fr-FR");',
  '  savePatients();',
  '  renderDashboard();',
  '  updateStepper(p);',
  '  showToast("PDF g\u00e9n\u00e9r\u00e9", "picture_as_pdf");',
  '}'
];

const newFn = lines.join('\n');

content = content.slice(0, start) + newFn + content.slice(end);
fs.writeFileSync('C:/Users/sebas/Desktop/ClaudeProjets/kinebilan/index.html', content, 'utf8');
console.log('Done');
