name = "kinebilan-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "71dff7636ec9bac7192e7b6f2f6a87f2"

[vars]
ALLOWED_EMAILS = "sp.mck.kine@gmail.com"

[[kv_namespaces]]
binding = "MAGIC_TOKENS"
id = "4e58b15778094e5b97b72970b24b989f"
