name = "kinebilan-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "71dff7636ec9bac7192e7b6f2f6a87f2"

[vars]
# ANTHROPIC_API_KEY doit être défini comme secret via : npx wrangler secret put ANTHROPIC_API_KEY
